# Copyright 2023 Manna Harbour
# https://github.com/eirrw/miryoku_zmk

name: 'Build Corne-ish Zen V2 Custom'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corneish_zen_v2_left","corneish_zen_v2_right"]'
      kconfig: '["CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y"]'
      branches: '["zmkfirmware/zmk/main caksoylar/zmk/caksoylar/zen-v1+v2+experimental"]'
